# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jacob's Blog
email: j-lgs@fake.email.dont.scrape.me
description: >- # this means to ignore newlines until "baseurl:"
  This site is Jacob Logan's blog, covering cybersecurity, linux, devops, homelabbing and more.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "blog.j-lgs.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DontCareAboutTwitter
github_username:  j-lgs
repository: j-lgs/blog
# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  - jekyll-feed

locale: "en-GB"

minimal_mistakes_skin: "contrast"
name: "Jacob Logan"

author:
  name: "Jacob Logan"
  avatar: "/assets/img/bio.webp"
  bio: >-
    Studying Cybersecurity.
    <3 Linux, WSL, Containers and Infrastructure, Configuration, Everything as code.
    This blog is for personal reference. Do not use it as documentation or attempt anything written here at home.
  location: Earth
  links:
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/j-lgs"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jacob-logan-859b38277/"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
